### ISSUE TITLE
NPM Install fails

### ISSUE THREAD

**Issue by rich-ware** [pheuter/essential-react#31]
I tried to run npm install essential-react. However, I get an error stating, "cannot find module webpack" . This template looks promising.

**Comment by pheuter** [comment]
Hm, interesting, I suspect it may have something to do with the `postinstall` npm run script since it's trying to build during postinstall of `react-router` before webpack is installed:

```
> npm install essential-react

> react-router@2.0.0 postinstall node_modules/react-router
> node ./npm-scripts/postinstall.js


> essential-react@0.4.0 postinstall node_modules/essential-react
> npm run build


> essential-react@0.4.0 build node_modules/essential-react
> webpack -p --progress --config webpack.production.config.js

sh: webpack: command not found
```

Perhaps it's a bug with NPM? Regardless, I haven't made it very clear in the README, but this template isn't designed to be installed as a node module, rather `git clone`'ed directly and used as a skeleton for your app. A Yeoman generator would be more relevant.
